### ISSUE TITLE
Complete Integrations Pain Points spreadsheet for FOLIO SysOps SIG

### ISSUE THREAD

**Issue by jwfuller** [culibraries/folio#33]
There is a [Google Sheet](https://docs.google.com/spreadsheets/d/1O8orRx2dBedaeWIkbN30v2ZHyRG6BgecLXgy5xL35bQ/edit?pli=1#gid=709776289) where institutions are listing integrations that are implemented or are planning to implement with any pain points they are experiencing. I have added a column to the spreadsheet for us to work in.

**Comment by libraryfemme** [comment]
When would you like this done by? Some of the issues are a bit complex, and I'm finding I need more time to consider them fully.

**Comment by nleboeuftrujillo** [comment]
You might want to add Juleah or the RM pod (Steve Brown) to answer the acquisitions lines.

**Comment by JuleahS** [comment]
I filled out the section for Acquisitions. EDIFACT is also a high need for us. I'm not sure what this all covers for the other libraries, but we use EDIFACT for both order records and invoices. We definitely want this by the time we go live. Otherwise we may need to manually input data or manually share information with our vendors. The section for Financial Integration appears to be for patron accounts and patron billing functions, not Acquisitions functions.

**Comment by esemenoff** [comment]
I looked at the cataloging lines, and I think we're ok there so far. OCLC seems to be working how we need it to at the moment, although that may change as we refine our cataloging processes in FOLIO over the next months. I don't know much about Z39.50, but I imagine we will need it for Prospector.

**Comment by jwfuller** [comment]
Our input for the spreadsheet is complete
