### ISSUE TITLE
Create UCB tenant and enable modules

### ISSUE THREAD

**Issue by jwfuller** [culibraries/folio#44]
- [x] Do not load sample data
- [x] Run as a Job inside the kubernetes cluster

**Comment by steveellis** [comment]
This is all handled by the folio-helm charts  in the `postJob`. The post job is a k8s batch job that runs inside of a container. [Here](https://github.com/folio-org/folio-helm/blob/ca437e194c2385867e5147d924664ac5dd8f06f0/mod-users/templates/post-install-job.yaml#L36) is the post job spec. This passes environment variables in for things we care about like `MODULE_VERSION` and then the container runs a [shell script](https://github.com/folio-org/folio-helm/blob/master/docker/folio-okapi-registration/create-deploy.sh) to deploy the module for the tenant.

The shell script grabs the module descriptor and the deployment descriptor from the registry and post it to okapi.

It also creates the tenant which apparently can run for each module registration without any problem.

I'm going to give this a try for the small set of modules that I'm working with. The goal is to see okapi start responding to requests with something more than "no tenant".

**Comment by steveellis** [comment]
Ok learning a few things:
* The order of enabling modules (the stuff that is in the `postJob` in the folio-helm chart) matters. If you try to enable `mod-authtoken` for example _before_ enabling mod-mod permissions you'll get errors about mod-authtoken depending on those interfaces. Need to study how this problem is solved in other deployments.
* This command `ALTER role $DB_USERNAME CREATEROLE CREATEDB SUPERUSER` matters a great deal. Without it modules will not enable because the user doesn't have the ability to create roles for the modules which handles creating their tables etc.
* Currently we have a this command running in a k8s job, but I think the first two commands fail, leading to the third not running. Unclear. Anyway I ran the command inside of pg and things started working.

**Comment by steveellis** [comment]
This was mostly completed by this: https://github.com/culibraries/folio/pull/133. Opened a new issue for bootstrapping the superuser (#135).

**Comment by steveellis** [comment]
This is now fully resolved by https://github.com/culibraries/folio/pull/138.
